### ISSUE TITLE
[HU] Consultar productos

### ISSUE THREAD

**Issue by josemip98** [josemip98/TFG#2]
Como usuario quiero poder consultar los productos disponibles.

**- Como:** Usuario

**- Quiero:** Consultar los productos disponibles en la aplicación.

**- Para:** Poder conocer la información nutricional de los productos.

**Tareas:**

- [x] Listado de productos
- [ ] Búsqueda 
- [x] Paginador

**Comment by JJ** [comment]
El "para" es en realidad lo que quiere hacer el usuario. El usuario quiere conocer la información nutricional de los productos. Tienes que definir también el contexto de "disponibles".
